### ISSUE TITLE
Maec/cybox related error

### ISSUE THREAD

**Issue by jamoiholland** [PaloAltoNetworks/pan-stix#13]
Issue running pan-stix under Ubuntu Desktop:
`./wildfire-to-stix.py --verbose -t wildfirecloud -f stix-il -h ad6c81f239d4b120758c1491c2a8c9aee1796c80e84c2660184617cab964b92e --sample` `network -o test-il.xml`
`Traceback (most recent call last):`
`  File "./wildfire-to-stix.py", line 26, in <module>`
`    import panstix.utils`
`  File "/home/jholland/pan-stix/panstix/utils.py", line 18, in <module>`
`    import maec.utils`
`  File "/usr/local/lib/python2.7/dist-packages/maec/__init__.py", line 9, in <module>`
`    from cybox import Entity as cyboxEntity`
`ImportError: cannot import name Entity`

Packages installed:
`adium-theme-ubuntu==0.3.4`
`beautifulsoup4==4.4.1`
`chardet==2.3.0`
`cybox==2.1.0.13`
`Cython==0.23.4`
`funcsigs==1.0.2`
`html5lib==0.999`
`importlib==1.0.4`
`lxml==3.7.2`
`maec==4.1.0.12`
`mixbox==1.0.1`
`mock==1.3.0`
`ordered-set==2.0.1`
`pan-python==0.7.0`
`pan-stix==0.2.4`
`pbr==1.10.0`
`python-dateutil==2.6.0`
`six==1.10.0`
`stix==1.2.0.2`
`unity-lens-photos==1.0`
`virtualenv==15.1.0`
`weakrefmethod==1.0.3`

**Comment by jtschichold** [comment]
@jamoiholland, please try with the following versions:

```
cybox==2.1.0.11
maec==4.1.0.12
stix==1.1.1.5
```
